# config/queries.yml
reports:
  - name: "war-art"
    search: "war"
    fields: ["id", "title", "artist_title", "date_display"]
    max_items: 25
    recipients: ["endavarangers@gmail.com"]

  - name: "impressionism-sample"
    search: "impressionism"
    fields: ["id", "title", "artist_title", "date_display"]
    max_items: 10
    recipients: ["stakeholders@example.com"]

  - name: "modern-art"
    search: "modern art"
    fields: ["id", "title", "artist_title", "date_display"]
    max_items: 15
    recipients: ["art-team@example.com"]

